channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.6.2
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - ipykernel=6.29.3
  - ipython=8.24.0
  - jedi=0.19.1
  - jupyter_client=8.6.2
  - jupyter_core=5.5.0
  - libcxx=14.0.6
  - libffi=3.4.4
  - libsodium=1.0.18
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.3.0
  - packaging=24.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.42
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.18.0
  - python=3.12.3
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tornado=6.3.3
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - filelock==3.14.0
      - fonttools==4.52.1
      - fsspec==2024.5.0
      - idna==3.7
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==1.26.4
      - onedrivedownloader==1.1.3
      - pandas==2.2.2
      - pillow==10.3.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - requests==2.32.2
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - sympy==1.12
      - threadpoolctl==3.5.0
      - torch==2.3.0
      - torchaudio==2.3.0
      - torchvision==0.18.0
      - tqdm==4.66.4
      - tzdata==2024.1
      - urllib3==2.2.1
